name: Intune Restore - Manual Trigger

on:
  # Allow manual trigger in Actions tab
  workflow_dispatch:

jobs:
  Intune-Full-Restore:
    runs-on: windows-latest
    steps:
      # 1. Check out the current repo (to access and update backup files)
      - uses: actions/checkout@v3

      # 2. Check out the IntuneManagement tool (specific version tag for stability)
      - uses: actions/checkout@v3
        with:
          repository: Micke-K/IntuneManagement
          path: ./IntuneManagement
          ref: 3.9.8 # use a known good release or latest tag

      # 3. Run IntuneManagement export (full tenant)
      - name: Import Intune config (Full)
        run: |
          Write-Host "Working directory: $(Get-Location)"
          #Show all files in the current directory for debugging
          $silentbatchFile = Get-ChildItem -filter "BulkImport.json" -recurse -File -erroraction SilentlyContinue
          if (-not $silentbatchFile) {
            Write-Host "BulkImport.json not found in repo directory. Please ensure it exists."
            exit 1
          }
          Write-Host "BulkImport.json content: $(Get-content $silentbatchFile.FullName)"
          $Env:AAD_TENANT_ID = "${{ secrets.AZURE_TENANT_ID }}"
          $Env:AAD_APP_ID = "${{ secrets.AZURE_CLIENT_ID }}"
          $Env:AAD_APP_SECRET = "${{ secrets.AZURE_CLIENT_SECRET }}"

          Write-Host "TenantId: $env:AAD_TENANT_ID"
          Write-Host "AppId: $env:AAD_APP_ID"
          Write-Host "AppSecret Length: $($env:AAD_APP_SECRET.Length)"

          $params = @{
            Silent           = $true
            Verbose          = $true
            SilentBatchFile  = $($silentbatchFile.FullName)
            TenantId         = $env:AAD_TENANT_ID
            AppId            = $env:AAD_APP_ID
            Secret           = $env:AAD_APP_SECRET
          }
          .\IntuneManagement\Start-IntuneManagement.ps1 @params
        shell: powershell